# mongod.conf                                                              
                                                                           
# for documentation of all options, see:                                   
#   http://docs.mongodb.org/manual/reference/configuration-options/        
                                                                           
# Where and how to store data.                                             
storage:                                                                                                          
  dbPath: /var/mongodb/db/                                                 
  journal:                                                                 
    enabled: true                                                          
#  engine:                                                                 
#  mmapv1:                                                                 
#  wiredTiger:                                                             
                                                                           
# where to write logging data.                                             
systemLog:                                                                 
  destination: file                                                        
  logAppend: true                                                                                             
  path: /var/mongodb/db/mongod.log                                         
                                                                           
# network interfaces                                                       
net:                                                                                                          
  port: 27000                                                              
  bindIp: 127.0.0.1,192.168.103.100                                        
                                                                           
                                                                           
# how the process runs                                                     
processManagement:                                                         
  #timeZoneInfo: /usr/share/zoneinfo                                       
  fork: true   

security:                                                                  
  authorization: enabled         
                                                                                                    
operationProfiling:                                                        
  mode: slowOp                                                             
  slowOpThresholdMs: 50                                                    
                                                                           
#replication:                                                              
                                                                           
#sharding:                                                                 
                                                                           
## Enterprise-Only Options:                                                
                                                                           
#auditLog:                                                                 
                                                                           
#snmp:                                                                                                                 
                                                                           
                                                                           